//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoalaTea_Project_Root
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTable
    {
        public tblTable()
        {
            this.tblTransactionItems = new HashSet<tblTransactionItem>();
        }
    
        public int TableID { get; set; }
        public int UserID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblTransactionItem> tblTransactionItems { get; set; }
    }
}
